<?php

/**
 * @file
 * Contains eric.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function eric_help($route_name, RouteMatchInterface $route_match)
{
  switch ($route_name) {
    // Main module help for the eric module.
    case 'help.page.eric':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Eric&#039;&#039;s Stuff') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function eric_theme()
{
  return [
    'eric' => [
      'render element' => 'children',
    ],
  ];
}
